name: Python checks

on:
    push:
        branches: ["main"]
        paths:
          - backend/**
    pull_request:
        # The branches below must be a subset of the branches above
        branches: ["main"]

jobs:
    ruff:
        name: Ruff check and linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  cd ./backend
                  python -m pip install --upgrade pip
                  pip install ruff
                  pip install mypy
            - name: Check style with Ruff
              run: |
                  cd ./backend
                  ruff check --output-format=github .
            - name: Check type hints with mypy
              run: |
                  cd ./backend
                  pip install .
                  mypy --show-error-codes beets_flask
            - name: Test with pytest
              run: |
                  cd ./backend
                  pip install .[test]
                  coverage run -m pytest  -v -s
